### PR TITLE
Percona toolkit

### PR DESCRIPTION
**Pull request by ghost**
#59 Added Percona Toolkit
percona-toolkit Does add a reference to mysql-common even if built from the percona repo.
Built both the master (percona) and the Toolkit Branch (percona-toolkit) after running update.sh Results below.  There is only a 34MB difference in size.

REPOSITORY | TAG | IMAGE ID | CREATED | SIZE 
percona-toolkit | 5.7 | f355eec22c74 | 3 minutes ago | 434MB
percona | 5.7 | fc8da26ed661 | 5 minutes ago | 400MB

### CODE REVIEW

**Comment by ghost** [comment]
@yosifkit Is this a more acceptable solution?

**Comment by yosifkit** [comment]
It is better, but I am still unsure about the extra 34 MB. What do you think @tianon?

**Comment by tianon** [comment]
Aren't these all essentially clients to Percona?  It seems some are even
clients to MongoDB, etc.  I think this would make more sense as a separate
variant or even a totally separate image.

**Comment by ghost** [comment]
@yosifkit and @tianon I have a solution that only adds about 5MB to the size of the image.  Not sure if this is better?  It still has to include one additional library from apt-get and that's libdbd-mysql-perl.  I could post a new merge request if we want now that I've tested it locally with my stuff.

**Comment by tianon** [comment]
Sorry for the delay -- I think this is still a little bit more than we're
comfortable with.  I _think_ it should be relatively easy to create a short
`Dockerfile` which is `FROM percona:5.7` and installs the toolkit though,
right?  Combined with automated builds (and repository links), that'd be an
easy way to have an up-to-date image of Percona with the toolkit installed.

**Comment by tianon** [comment]
Closing given the above (and the positive discussion happening over in https://github.com/docker-library/percona/issues/68). :+1:

**Pull request closed without merging**
