### PR TITLE
Ability to run slaves in super-read-only mode

### PR DESCRIPTION
**Pull request by baloo**
Slaves should be able to start in super-read-only mode[1](https://www.percona.com/doc/percona-server/5.6/management/super_read_only.html). Adds a
`MYSQL_SUPER_READ_ONLY` environment variable to basically skips all
user/timezone setup.

This is intended to be used with `/docker-entrypoint-initdb.d/` files like:

```
CHANGE MASTER TO MASTER_HOST="master", MASTER_USER="replication", MASTER_CONNECT_RETRY=2, MASTER_RETRY_COUNT=0;
```

### CODE REVIEW

**Comment by baloo** [comment]
This should fix #26 as well

**Comment by baloo** [comment]
It has not been added in 5.5 because the setting is not available before 5.6.

**Comment by yosifkit** [comment]
Closing old PR

**Comment by baloo** [comment]
@yosifkit I would have appreciated a review instead :D

**Comment by baloo** [comment]
nevermind, just seen this repo has been deprecated.

**Pull request closed without merging**
